name: Create Pull Request

on:
  push:               # Optionally trigger on push to a specific branch (e.g., main)
    branches:
      - main

jobs:
  create-branch-and-pr:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Fetch all branches

    # Step 5: Create a Pull Request from the new branch to another branch
      # Create Pull Request
    - name: Create Pull Requests
      uses: peter-evans/create-pull-request@v5
      with:
        base: main
        commit-message: "Generate baseline profiles"
        title: "Generate baseline profiles"
        branch: new/changes
        delete-branch: true
        body: "This is an automated pull request to merge changes from $NEW_BRANCH to main."


