name: Create Pull Request

on:
  workflow_dispatch:

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "Github actions"
          git config user.email "actions@github.com"

      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Automated commit message'
          branch: 'dev'  # Source branch for the PR
          base: 'main'  # Target branch for the PR
          title: 'Automated PR from GitHub Actions'
          body: 'This PR was created automatically by GitHub Actions.'
          labels: 'automated-pr'