name: Create a sample pr

on:
  workflow_dispatch:

jobs:
  create-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create a file
        run: echo "Hello, World!" > hello1.txt

      - name: Show created file
        run: cat hello1.txt

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          commit-message: "Newly created file"
          title: "Newly created file"
          delete-branch: true
          branch: actions/baseline-profiles
